name: Build React Native Android APK

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install npm dependencies
      - name: Install dependencies
        run: |
          npm install

      # 4️⃣ Setup Java JDK (for Gradle)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 5️⃣ Setup Android SDK environment
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6️⃣ Give Gradle wrapper execute permission
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 7️⃣ Build the Android debug APK
      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 8️⃣ Upload the generated APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
