name: Build WPPConnect Mobile APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm uninstall -g react-native-cli || true

      - name: Prepare Gradle
        run: chmod +x android/gradlew

      - name: Build Android APK
        env:
          CI: true
          NODE_OPTIONS: --no-warnings
          REACT_NATIVE_CLI_PATH: node_modules/@react-native-community/cli/build/bin.js
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wppconnect-mobile-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
